import "./js/jenis-keuangan.js";
import { db, auth } from "./firebase-config.js";
import { collection, onSnapshot, query, where } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";

let semuaPemasukan=[],semuaPengeluaran=[],semuaSiswaSiswi=[],userAktif=null;
let unsubscribePemasukan=null,unsubscribeExpenses=null,unsubscribeSiswaSiswi=null;
let pemasukanReady=false,expensesReady=false,siswaSiswiReady=false;
const $=id=>document.getElementById(id);
const LOGO_DEFAULT="Photoroom_20260812_224807.png?v=20260826";
function settings(){try{if(window.CatatanKasSettings?.get)return window.CatatanKasSettings.get();const u=userAktif?.uid;const k=u?`pengaturanAplikasi_${u}`:"pengaturanAplikasi";return JSON.parse(localStorage.getItem(k)||"{}")||{}}catch(_){return {}}}
function lembagaAktif(){const s=settings();return String(s.namaPondok||s.namaLembaga||s.lembaga||"").trim()}
function logoDashboardTersimpan(){return LOGO_DEFAULT}
function terapkanIdentitasDashboard(){const s=settings(),nama=lembagaAktif(),title=nama||"Keuangan",subtitle=String(s.subJudul||s.subjudul||"").trim()||"Dashboard Keuangan";document.querySelectorAll(".app-name,[data-app-name]").forEach(e=>e.textContent=title);document.querySelectorAll(".app-subtitle,[data-app-subtitle]").forEach(e=>e.textContent=subtitle);document.title=nama?`${nama} | Keuangan`:"Keuangan | Dashboard"}
function muatLogoDashboard(){const logo=logoDashboardTersimpan();document.querySelectorAll(".app-logo,.ck-logo,#logoDashboard,#dashboardLogo,#logoPreviewV2,#logoPreview,#previewLogoDashboard,img[alt='Logo Dashboard'],img[alt='Logo aplikasi'],img[alt='Logo Catatan Kas'],[data-dashboard-logo]").forEach(e=>{if(e?.tagName==="IMG"){e.removeAttribute("srcset");e.removeAttribute("data-src");e.dataset.logoSource="official-20260826";if(e.src!==new URL(logo,document.baseURI).href)e.src=logo}})}
function refreshLogoDanDashboard(){muatLogoDashboard();terapkanIdentitasDashboard();tampilkanDashboard()}
function rupiah(v){return "Rp"+(Number(v)||0).toLocaleString("id-ID")}
const ambilNominal=i=>Number(i?.nominal??i?.jumlah??i?.nilai??0)||0;
const ambilNominalPengeluaran=i=>Number(i?.nominal??i?.jumlah??i?.nilai??i?.harga??i?.total??0)||0;
const ambilKategoriPemasukan=i=>String(i?.jenis??i?.kategori??"").trim();
const ambilKategoriPengeluaran=i=>String(i?.jenis??i?.kategori??i?.keterangan??"").trim();
const ambilLembaga=i=>String(i?.lembagaNama??i?.lembaga??i?.namaLembaga??"").trim();
const cocok=(v,f)=>!f||f==="Semua"||String(v).trim().toLowerCase()===String(f).trim().toLowerCase();
function lembagaOptions(){const active=lembagaAktif(),list=[...new Set([...semuaPemasukan,...semuaPengeluaran].map(ambilLembaga).filter(Boolean))];if(active&&!list.some(x=>x.toLowerCase()===active.toLowerCase()))list.push(active);return list.sort((a,b)=>a.localeCompare(b,"id"))}
function pasangFilterLembaga(){let el=$("filterLembaga"),jenis=$("filterKategori");if(!jenis)return;if(!el){const wrap=document.createElement("div");wrap.id="filterLembagaWrap";wrap.className="mb-3";wrap.innerHTML='<label class="form-label fw-semibold" for="filterLembaga">Lembaga</label><select id="filterLembaga" class="form-select"><option value="Semua">Semua Lembaga</option></select>';const anchor=jenis.closest(".card")||jenis.parentElement;anchor?.parentElement?.insertBefore(wrap,anchor);el=wrap.querySelector("#filterLembaga");el.onchange=()=>tampilkanDashboard()}const current=el.value||"Semua";el.innerHTML='<option value="Semua">Semua Lembaga</option>';lembagaOptions().forEach(x=>{const o=document.createElement("option");o.value=x;o.textContent=x;el.appendChild(o)});if([...el.options].some(o=>o.value.toLowerCase()===current.toLowerCase()))el.value=current;else el.value="Semua"}
function sinkronkanFilterKategori(){const el=$("filterKategori");if(el&&window.ckJenisKeuangan)window.ckJenisKeuangan.populate(el)}
function hitungDashboard(){const filter=$("filterKategori")?.value||"Semua",lembaga=$("filterLembaga")?.value||"Semua",pemasukan=semuaPemasukan.filter(i=>cocok(ambilLembaga(i),lembaga)),expenses=semuaPengeluaran.filter(i=>cocok(ambilLembaga(i),lembaga));const totalMasuk=pemasukan.filter(i=>cocok(ambilKategoriPemasukan(i),filter)).reduce((s,i)=>s+ambilNominal(i),0),totalKeluar=expenses.filter(i=>cocok(ambilKategoriPengeluaran(i),filter)).reduce((s,i)=>s+ambilNominalPengeluaran(i),0);return{totalMasuk,totalKeluar,saldo:totalMasuk-totalKeluar,totalSiswaSiswi:semuaSiswaSiswi.length,filter,lembaga,uid:userAktif?.uid||null,loading:!(pemasukanReady&&expensesReady&&siswaSiswiReady)}}
function tampilkanDashboard(){sinkronkanFilterKategori();pasangFilterLembaga();const h=hitungDashboard();["totalMasuk","pemasukan","jumlahPemasukan"].forEach(id=>{if($(id))$(id).textContent=rupiah(h.totalMasuk)});["totalKeluar","pengeluaran","jumlahPengeluaran"].forEach(id=>{if($(id))$(id).textContent=rupiah(h.totalKeluar)});["totalSaldo","saldo","saldoSaatIni"].forEach(id=>{if($(id))$(id).textContent=rupiah(h.saldo)});["totalSiswaSiswi","totalSantri","jumlahSiswaSiswi"].forEach(id=>{if($(id))$(id).textContent=h.totalSiswaSiswi.toLocaleString("id-ID")});window.catatanKasDashboard=h}
function berhentiListener(){[unsubscribePemasukan,unsubscribeExpenses,unsubscribeSiswaSiswi].forEach(fn=>{try{fn?.()}catch(_){}});unsubscribePemasukan=unsubscribeExpenses=unsubscribeSiswaSiswi=null;pemasukanReady=expensesReady=siswaSiswiReady=false}
function mulaiPemasukan(){unsubscribePemasukan?.();if(!userAktif)return;unsubscribePemasukan=onSnapshot(query(collection(db,"payments"),where("uid","==",userAktif.uid)),s=>{semuaPemasukan=s.docs.map(d=>({id:d.id,...d.data()}));pemasukanReady=true;tampilkanDashboard();window.dispatchEvent(new CustomEvent("dataKeuanganBerubah",{detail:{tipe:"pemasukan",uid:userAktif.uid}}))},e=>{console.error("Pemasukan Dashboard:",e);pemasukanReady=false;window.dispatchEvent(new CustomEvent("dashboardDataError",{detail:{tipe:"pemasukan",uid:userAktif.uid,error:e}}));tampilkanDashboard()})}
function mulaiPengeluaran(){unsubscribeExpenses?.();if(!userAktif)return;unsubscribeExpenses=onSnapshot(query(collection(db,"expenses"),where("uid","==",userAktif.uid)),s=>{semuaPengeluaran=s.docs.map(d=>({id:d.id,...d.data()}));expensesReady=true;tampilkanDashboard();window.dispatchEvent(new CustomEvent("dataKeuanganBerubah",{detail:{tipe:"pengeluaran",uid:userAktif.uid}}))},e=>{console.error("Pengeluaran Dashboard:",e);expensesReady=false;window.dispatchEvent(new CustomEvent("dashboardDataError",{detail:{tipe:"pengeluaran",uid:userAktif.uid,error:e}}));tampilkanDashboard()})}
function mulaiSiswaSiswi(){unsubscribeSiswaSiswi?.();if(!userAktif)return;unsubscribeSiswaSiswi=onSnapshot(query(collection(db,"santri"),where("uid","==",userAktif.uid)),s=>{semuaSiswaSiswi=s.docs.map(d=>({id:d.id,...d.data(),source:"firestore"}));siswaSiswiReady=true;tampilkanDashboard()},e=>{console.error("Daftar Nama Dashboard:",e);siswaSiswiReady=false;window.dispatchEvent(new CustomEvent("dashboardDataError",{detail:{tipe:"siswaSiswi",uid:userAktif.uid,error:e}}));tampilkanDashboard()})}
window.refreshDashboard=refreshLogoDanDashboard;window.addEventListener("dataKeuanganBerubah",()=>tampilkanDashboard());window.addEventListener("pemasukanBerubah",()=>tampilkanDashboard());window.addEventListener("refreshDashboard",refreshLogoDanDashboard);window.addEventListener("logoDashboardChanged",muatLogoDashboard);window.addEventListener("settingsChanged",()=>{terapkanIdentitasDashboard();muatLogoDashboard();tampilkanDashboard()});
function pasangFilter(){const f=$("filterKategori");if(f)f.addEventListener("change",tampilkanDashboard)}
function initApp(){pasangFilter();muatLogoDashboard();terapkanIdentitasDashboard();tampilkanDashboard()}
onAuthStateChanged(auth,u=>{berhentiListener();userAktif=u||null;semuaPemasukan=[];semuaPengeluaran=[];semuaSiswaSiswi=[];if(userAktif){setTimeout(()=>{terapkanIdentitasDashboard();muatLogoDashboard();mulaiPemasukan();mulaiPengeluaran();mulaiSiswaSiswi()},0)}tampilkanDashboard()});
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initApp);else initApp();
